### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by jgcodes2020** [revmischa/sdl3-rs#15]
SDL 3 recently reached pre-release status, and this library hasn't been updated in a few months.

**Comment by revmischa** [comment]
I'm not actively working on it but would be great to get moving on it. Looks like https://crates.io/crates/sdl3-sys is ready to be used in a more stable fashion. Contributions welcome!

**Comment by revmischa** [comment]
Doing some updates now:
https://github.com/revmischa/sdl3-rs/commit/4333cdc6d2eb841f8fd8f24cf7d26d29dd94ecb4
https://github.com/revmischa/sdl3-rs/pull/17
