### ISSUE TITLE
macos Apple silicon build fail: `Undefined symbols: _SDL_CreateWindowWithPosition`

### ISSUE THREAD

**Issue by tcosmo** [revmischa/sdl3-rs#19]
Hello, 

I have installed SDL3 on my mac (macbook pro M3 max, macos 14.2.1), and I am able to compile and run [this "minimal" c++ SDL3 example](https://github.com/Ravbug/sdl3-sample).

I'm trying to build the minimal rust example [given here](https://docs.rs/sdl3/latest/sdl3/#getting-started).

However, when I do `cargo run` I get the following linking error:

```
  = note: ld: Undefined symbols:
            _SDL_CreateWindowWithPosition, referenced from:
                sdl3::video::WindowBuilder::build::h922fc6311cc9e14a in libsdl3-0c9d2b93f1e76985.rlib[5](sdl3-0c9d2b93f1e76985.sdl3.8e5aba5ed58df8e4-cgu.2.rcgu.o)
```

Would you have any ideas?

Thank you!

**Comment by revmischa** [comment]
Sure, we're pretty far away from having current SDL3 building correctly. It's a work in progress, not ready to use yet. It's an open source project to update the bindings here to match the current semi-stable version of libsdl3.
I will update the README soon to reflect this. 
Please hang tight before trying to use SDL3 with your project, but we're always looking for volunteers to help with the migration if you want it sooner!

**Comment by tcosmo** [comment]
Thank you for your answer! OK we'll hang tight :)
