### ISSUE TITLE
Enabling "raw-window-handle" feature causes compilation errors

### ISSUE THREAD

**Issue by What42Pizza** [revmischa/sdl3-rs#51]
I'm kinda new to this so I'm not sure if I'm doing something wrong, but adding this to the deps of an empty project: `sdl3 = { git = "https://github.com/revmischa/sdl3-rs.git", features = ["raw-window-handle"] }` (or just version = "0.11.9") causes build errors for me. I've used cargo-cache and `cargo clean` to clear and reset everything, and I still have these errors. For context, I'm looking into sdl3 + wgpu and I don't see any other way to make the example code work, though I don't really have any plans to use this at the moment. If needed, here are the errors I have: https://pastebin.com/VpmXF4td

**Comment by What42Pizza** [comment]
Also, is it just me or does wgpu-hal-0.14.1 not compile either? I keep getting the error `expected 'winapi::ctypes::c_void', found 'std::ffi::c_void'` every time I clear cargo's registry cache and I have to fix it manually every time

**Comment by What42Pizza** [comment]
Also I've seen a lot of compilation errors in the tests, and when I fixed those, I got a ton of compilation errors in the examples. I think I've fixed them all and I have 32/35 tests passing with `cargo test --features build-from-source`, would you like me to open a pr?

**Comment by revmischa** [comment]
Yes please, would love to have the tests and examples fixed!

Regarding the compilation issues with raw-window-handle, I don't have windows so I haven't tested them. I'm sure the conditional compilation features for windows need to be updated.
For references in sys::* I would search the sdl3-sys docs. For example searching for `SDL_PROP_WINDOW_WIN32_HINSTANCE_POINTER` I found https://docs.rs/sdl3-sys/latest/sdl3_sys/video/constant.SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER.html - perhaps they are the same thing?

I don't know what the difference is between a `winapi::ctypes::c_void` and `std::ffi::c_void` but probably both are just "no type info at all, good luck"

**Comment by What42Pizza** [comment]
Fixed with pull https://github.com/revmischa/sdl3-rs/pull/52
