### ISSUE TITLE
Wgpu example crashes when resized

### ISSUE THREAD

**Issue by What42Pizza** [revmischa/sdl3-rs#55]
I've already found the fix for this but it's not worth a pr, you just need to change line 132 in the wgpu example to this: `win_event: WindowEvent::PixelSizeChanged(width, height) | WindowEvent::Resized(width, height),`

**Comment by revmischa** [comment]
Okay, want to fork the repo and change it there then open a PR from your master to my master? Might be easier for these sorts of changes

**Comment by What42Pizza** [comment]
Fixed with https://github.com/revmischa/sdl3-rs/pull/60
